[build]
  buildCommand = "go build -o out main.go"

[start]
  startCommand = "./out"

[env]
  MONGO_URI = "mongodb+srv://ashish:V%40Mongodb.1@cluster0.ldtmehf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  GOOGLE_MAPS_API_KEY = "AIzaSyA1Rz_xGPNYMO7WyP1wYdVzVoMOCO_UUtQ"
